### ISSUE TITLE
WHEN IS GIANT LIBRARY DONEEE

### ISSUE THREAD

**Issue by aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa4** [Eating-simulator/Eating-simulator.github.io#12]
Where is giant librayr

**Comment by ghost** [comment]
i finished it ask Jonathan

**Comment by aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa4** [comment]
okie

**Comment by jondoglover** [comment]
can InfinityDude edit without asking

**Comment by ghost** [comment]
wdym

**Comment by ghost** [comment]
[glibrary 6.txt](https://github.com/Eating-simulator/Eating-simulator.github.io/files/5205260/glibrary.6.txt)
[glibrary 7.txt](https://github.com/Eating-simulator/Eating-simulator.github.io/files/5205261/glibrary.7.txt)
[glibrary 5.txt](https://github.com/Eating-simulator/Eating-simulator.github.io/files/5205262/glibrary.5.txt)

**Comment by jondoglover** [comment]
wait you mean the library ASCII
I thought it was about me making you able to access the library
PHEW

**Comment by jondoglover** [comment]
what's the wontfix
I will fix

**Comment by aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa4** [comment]
okie
